# Generated by Django 4.0.2 on 2022-02-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeling',
            name='strength',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='thought',
            name='basis',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='thought',
            name='counter_evidence',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
