# Generated by Django 4.0.2 on 2022-02-28 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0002_feeling_strength_thought_basis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewFeeling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.IntegerField(null=True)),
                ('feel_variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbt.feelvariation')),
                ('thought', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbt.thought')),
            ],
        ),
    ]
